
// to check server is running
GET http://localhost:4000/health

###


// to get all bus list
GET http://localhost:4000/api/v1/bus
###

// to get Root Id And all bus for specific Root
GET http://localhost:4000/api/v1/root?from=dhaka&to=khulna
###

// SignUp
POST http://localhost:4000/api/v1/user/signup
Content-Type:  application/json

{
    "name" : "mahim",
    "phone" : "01211100103",
    "email" : "itsarif@gmail.com",
    "password" : "12345"
}

### 
// SignIn as Admin
POST http://localhost:4000/api/v1/user/signin
Content-Type:  application/json

{
    "email" : "admin@test.com",
    "password" : "12345"
}

### 
// SignIn as User
POST http://localhost:4000/api/v1/user/signin
Content-Type:  application/json

{
    "email" : "user@test.com",
    "password" : "12345"
}

### 
// Sample Book a ticket
POST http://localhost:4000/api/v1/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTFhNDE0NGY4OWUzMmEzYTRlZTcyOWYiLCJ1c2VyUm9sZSI6IkNsaWVudCIsImlhdCI6MTY5NjM0NDM5MSwiZXhwIjoxNjk2MzQ3OTkxfQ.9umwf97lilRLUf6O9Wq_u5aPIaua9z4_BtpzOmYH4jY

{
    "rootId" : "", 
    "busId" : "",
    
    "date" : "isoDateString",
    "quantity" : 1,
    "totalPrice" : 560
}

### 
// Sample Book a ticket
get http://localhost:4000/api/v1/ticket
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTFhNDE0NGY4OWUzMmEzYTRlZTcyOWYiLCJ1c2VyUm9sZSI6IkNsaWVudCIsImlhdCI6MTY5NjM0NDM5MSwiZXhwIjoxNjk2MzQ3OTkxfQ.9umwf97lilRLUf6O9Wq_u5aPIaua9z4_BtpzOmYH4jY

### 
// Sample Book a ticket
delete http://localhost:4000/api/v1/ticket?id=651c2965aa611dcbb0297da4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTFhNDE0NGY4OWUzMmEzYTRlZTcyOWYiLCJ1c2VyUm9sZSI6IkNsaWVudCIsImlhdCI6MTY5NjM0NDM5MSwiZXhwIjoxNjk2MzQ3OTkxfQ.9umwf97lilRLUf6O9Wq_u5aPIaua9z4_BtpzOmYH4jY


